services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ 'entrypoint.sh' ]
    volumes:
      - .:/app
      - static_volume:/home/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:14.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.24-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.nginx/http.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.nginx/ssl-dhparam.pem:/etc/nginx/ssl-dhparam.pem:ro
      - certs:/etc/nginx/ssl:ro
      - certbot-www:/var/www/certbot:ro
      - static_volume:/home/app/static:ro

  certbot:
    image: certbot/certbot:v2.6.0
    volumes:
      - certs:/etc/letsencrypt
      - certbot-www:/var/lib/letsencrypt
    command: renew
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  static_volume:
  media_volume:
  postgres_data:
  certs:
  certbot-www:
