# Generated by Django 5.2.3 on 2025-06-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=255, verbose_name="Сервис")),
                ("full_name", models.CharField(max_length=255, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone_number",
                    models.CharField(max_length=40, verbose_name="Телефон"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Компания"),
                ),
                (
                    "markets_of_interest",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Market of interest"
                    ),
                ),
                (
                    "mode",
                    models.CharField(blank=True, max_length=255, verbose_name="Mode"),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Industry"
                    ),
                ),
                (
                    "temperature_requirement",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Temperature Requirement",
                    ),
                ),
                (
                    "pallet_positions_requested",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Pallet Positions Requested"
                    ),
                ),
                (
                    "anticipated_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Anticipated Start Date"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "how_did_you_hear_about_us",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="How did you hear about us",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact request",
                "verbose_name_plural": "Contact requests",
            },
        ),
    ]
