# Generated by Django 5.2.3 on 2025-06-23 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(default='new', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='updated',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
