# Generated by Django 5.2.3 on 2025-06-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_contactrequest_created_contactrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
